In [6]:
import pandas as pd
from datetime import datetime, timezone


import papermill as pm

In [7]:
pm.execute_notebook('data_consolidation.ipynb', 'data_consolidation_output.ipynb')

Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

{'cells': [{'cell_type': 'code',
   'execution_count': 1,
   'id': '908b51fe',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:04.672995+00:00',
     'end_time': '2026-03-12T17:02:05.697185+00:00',
     'duration': 1.02419,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:04.676962Z',
     'iopub.execute_input': '2026-03-12T17:02:04.677179Z',
     'iopub.status.idle': '2026-03-12T17:02:05.696225Z',
     'shell.execute_reply': '2026-03-12T17:02:05.695959Z'}},
   'outputs': [],
   'source': '# Imports\nimport pandas as pd\nimport papermill as pm #papermill allows us to execute notebooks not just .py files.\nimport fred_data_download as fred_data_download'},
  {'cell_type': 'code',
   'execution_count': 2,
   'id': '79aba66c',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:05.699520+00:00',
     'end_time': '2026-03-12T17:02:11.572513+00:00',
     'duration': 5.872993,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:05.701707Z',
     'iopub.execute_input': '2026-03-12T17:02:05.702030Z',
     'iopub.status.idle': '2026-03-12T17:02:11.570936Z',
     'shell.execute_reply': '2026-03-12T17:02:11.570489Z'}},
   'outputs': [{'output_type': 'display_data',
     'metadata': {},
     'data': {'text/plain': 'Executing:   0%|          | 0/4 [00:00<?, ?cell/s]',
      'application/vnd.jupyter.widget-view+json': {'version_major': 2,
       'version_minor': 0,
       'model_id': '61f373cb26c249aa997935ac492cb66a'}}},
    {'output_type': 'display_data',
     'metadata': {},
     'data': {'text/plain': 'Executing:   0%|          | 0/1 [00:00<?, ?cell/s]',
      'application/vnd.jupyter.widget-view+json': {'version_major': 2,
       'version_minor': 0,
       'model_id': 'e4be14249d664d0ba796df840411308c'}}},
    {'output_type': 'stream',
     'name': 'stdout',
     'text': '            3m_treasury  2yr_treasury  10yr_treasury  yield_curve    VIX  \\\ndate                                                                       \n2025-07-30         4.41          3.94           4.38         0.44  15.48   \n2025-07-31         4.41          3.94           4.37         0.43  16.72   \n2025-08-01         4.35          3.69           4.23         0.54  20.38   \n2025-08-02          NaN           NaN            NaN          NaN    NaN   \n2025-08-03          NaN           NaN            NaN          NaN    NaN   \n\n            fed_funds_rate  \ndate                        \n2025-07-30            4.33  \n2025-07-31            4.33  \n2025-08-01            4.33  \n2025-08-02            4.33  \n2025-08-03            4.33  \n'}],
   'source': "#Execute child notebooks\npm.execute_notebook('SP500_notebook.ipynb', 'SP500_notebook_output.ipynb')\npm.execute_notebook('SP500futures_notebook.ipynb', 'SP500futures_notebook_output.ipynb')\nfred_data_download.run_fred_download()\n"},
  {'cell_type': 'code',
   'execution_count': 3,
   'id': 'c1fdde5e',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.577005+00:00',
     'end_time': '2026-03-12T17:02:11.586125+00:00',
     'duration': 0.00912,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.580570Z',
     'iopub.execute_input': '2026-03-12T17:02:11.580817Z',
     'iopub.status.idle': '2026-03-12T17:02:11.585122Z',
     'shell.execute_reply': '2026-03-12T17:02:11.583661Z'}},
   'outputs': [],
   'source': '#'},
  {'cell_type': 'code',
   'execution_count': 4,
   'id': 'e550a085',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.587781+00:00',
     'end_time': '2026-03-12T17:02:11.638716+00:00',
     'duration': 0.050935,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.589579Z',
     'iopub.execute_input': '2026-03-12T17:02:11.589730Z',
     'iopub.status.idle': '2026-03-12T17:02:11.637860Z',
     'shell.execute_reply': '2026-03-12T17:02:11.637563Z'}},
   'outputs': [],
   'source': "# Pull DFS\nsp = pd.read_parquet('SP500_data.parquet')\nfred = pd.read_parquet('fred_data.parquet')\nfutures = pd.read_csv('Overnight_SP500_data.csv')"},
  {'cell_type': 'code',
   'execution_count': 5,
   'id': '674a6ee8',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.639998+00:00',
     'end_time': '2026-03-12T17:02:11.645754+00:00',
     'duration': 0.005756,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.641370Z',
     'iopub.execute_input': '2026-03-12T17:02:11.641487Z',
     'iopub.status.idle': '2026-03-12T17:02:11.645111Z',
     'shell.execute_reply': '2026-03-12T17:02:11.644878Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 225 entries, 2025-07-30 to 2026-03-11\nData columns (total 6 columns):\n #   Column          Non-Null Count  Dtype  \n---  ------          --------------  -----  \n 0   3m_treasury     152 non-null    float64\n 1   2yr_treasury    152 non-null    float64\n 2   10yr_treasury   152 non-null    float64\n 3   yield_curve     153 non-null    float64\n 4   VIX             159 non-null    float64\n 5   fed_funds_rate  224 non-null    float64\ndtypes: float64(6)\nmemory usage: 12.3 KB\n"}],
   'source': 'fred.info()'},
  {'cell_type': 'code',
   'execution_count': 6,
   'id': '289d6a4c',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.647026+00:00',
     'end_time': '2026-03-12T17:02:11.652557+00:00',
     'duration': 0.005531,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.648404Z',
     'iopub.execute_input': '2026-03-12T17:02:11.648501Z',
     'iopub.status.idle': '2026-03-12T17:02:11.651672Z',
     'shell.execute_reply': '2026-03-12T17:02:11.651415Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 154 entries, 2025-07-30 to 2026-03-10\nData columns (total 6 columns):\n #   Column        Non-Null Count  Dtype  \n---  ------        --------------  -----  \n 0   Close         154 non-null    float64\n 1   High          154 non-null    float64\n 2   Low           154 non-null    float64\n 3   Open          154 non-null    float64\n 4   Volume        154 non-null    int64  \n 5   Day Change %  154 non-null    float64\ndtypes: float64(5), int64(1)\nmemory usage: 8.4 KB\n"}],
   'source': 'sp.info()'},
  {'cell_type': 'code',
   'execution_count': 7,
   'id': 'c685226a',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.654060+00:00',
     'end_time': '2026-03-12T17:02:11.658353+00:00',
     'duration': 0.004293,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.655741Z',
     'iopub.execute_input': '2026-03-12T17:02:11.655881Z',
     'iopub.status.idle': '2026-03-12T17:02:11.657545Z',
     'shell.execute_reply': '2026-03-12T17:02:11.657275Z'}},
   'outputs': [],
   'source': "fred.index.name = 'Date'"},
  {'cell_type': 'code',
   'execution_count': 8,
   'id': '8629418f',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.659787+00:00',
     'end_time': '2026-03-12T17:02:11.665935+00:00',
     'duration': 0.006148,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.661653Z',
     'iopub.execute_input': '2026-03-12T17:02:11.661795Z',
     'iopub.status.idle': '2026-03-12T17:02:11.665224Z',
     'shell.execute_reply': '2026-03-12T17:02:11.664946Z'}},
   'outputs': [],
   'source': "#Perform Left join on date to consolidate dataframes for modeling.\ndata = pd.merge(sp, fred, on='Date', how='left')"},
  {'cell_type': 'code',
   'execution_count': 9,
   'id': '4da00558',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.667848+00:00',
     'end_time': '2026-03-12T17:02:11.677214+00:00',
     'duration': 0.009366,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.670376Z',
     'iopub.execute_input': '2026-03-12T17:02:11.670518Z',
     'iopub.status.idle': '2026-03-12T17:02:11.676542Z',
     'shell.execute_reply': '2026-03-12T17:02:11.676274Z'}},
   'outputs': [{'output_type': 'execute_result',
     'metadata': {},
     'data': {'text/plain': '                  Close         High          Low         Open      Volume  \\\nDate                                                                         \n2025-07-30  6362.899902  6396.540039  6336.379883  6381.229980  5375070000   \n2025-07-31  6339.390137  6427.020020  6327.640137  6427.020020  6077080000   \n2025-08-01  6238.009766  6287.279785  6212.689941  6287.279785  5827150000   \n2025-08-04  6329.939941  6330.689941  6271.709961  6271.709961  4842580000   \n2025-08-05  6299.189941  6346.000000  6289.370117  6336.629883  5517410000   \n\n            Day Change %  3m_treasury  2yr_treasury  10yr_treasury  \\\nDate                                                                 \n2025-07-30     -0.287250         4.41          3.94           4.38   \n2025-07-31     -1.363461         4.41          3.94           4.37   \n2025-08-01     -0.783646         4.35          3.69           4.23   \n2025-08-04      0.928455         4.35          3.69           4.22   \n2025-08-05     -0.590849         4.34          3.72           4.22   \n\n            yield_curve    VIX  fed_funds_rate  \nDate                                            \n2025-07-30         0.44  15.48            4.33  \n2025-07-31         0.43  16.72            4.33  \n2025-08-01         0.54  20.38            4.33  \n2025-08-04         0.53  17.52            4.33  \n2025-08-05         0.50  17.85            4.33  ',
      'text/html': '<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Close</th>\n      <th>High</th>\n      <th>Low</th>\n      <th>Open</th>\n      <th>Volume</th>\n      <th>Day Change %</th>\n      <th>3m_treasury</th>\n      <th>2yr_treasury</th>\n      <th>10yr_treasury</th>\n      <th>yield_curve</th>\n      <th>VIX</th>\n      <th>fed_funds_rate</th>\n    </tr>\n    <tr>\n      <th>Date</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2025-07-30</th>\n      <td>6362.899902</td>\n      <td>6396.540039</td>\n      <td>6336.379883</td>\n      <td>6381.229980</td>\n      <td>5375070000</td>\n      <td>-0.287250</td>\n      <td>4.41</td>\n      <td>3.94</td>\n      <td>4.38</td>\n      <td>0.44</td>\n      <td>15.48</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-07-31</th>\n      <td>6339.390137</td>\n      <td>6427.020020</td>\n      <td>6327.640137</td>\n      <td>6427.020020</td>\n      <td>6077080000</td>\n      <td>-1.363461</td>\n      <td>4.41</td>\n      <td>3.94</td>\n      <td>4.37</td>\n      <td>0.43</td>\n      <td>16.72</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-01</th>\n      <td>6238.009766</td>\n      <td>6287.279785</td>\n      <td>6212.689941</td>\n      <td>6287.279785</td>\n      <td>5827150000</td>\n      <td>-0.783646</td>\n      <td>4.35</td>\n      <td>3.69</td>\n      <td>4.23</td>\n      <td>0.54</td>\n      <td>20.38</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-04</th>\n      <td>6329.939941</td>\n      <td>6330.689941</td>\n      <td>6271.709961</td>\n      <td>6271.709961</td>\n      <td>4842580000</td>\n      <td>0.928455</td>\n      <td>4.35</td>\n      <td>3.69</td>\n      <td>4.22</td>\n      <td>0.53</td>\n      <td>17.52</td>\n      <td>4.33</td>\n    </tr>\n    <tr>\n      <th>2025-08-05</th>\n      <td>6299.189941</td>\n      <td>6346.000000</td>\n      <td>6289.370117</td>\n      <td>6336.629883</td>\n      <td>5517410000</td>\n      <td>-0.590849</td>\n      <td>4.34</td>\n      <td>3.72</td>\n      <td>4.22</td>\n      <td>0.50</td>\n      <td>17.85</td>\n      <td>4.33</td>\n    </tr>\n  </tbody>\n</table>\n</div>'},
     'execution_count': 9}],
   'source': 'data.head()'},
  {'cell_type': 'code',
   'execution_count': 10,
   'id': 'edf2eae5',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.678998+00:00',
     'end_time': '2026-03-12T17:02:11.688743+00:00',
     'duration': 0.009745,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.681428Z',
     'iopub.execute_input': '2026-03-12T17:02:11.681846Z',
     'iopub.status.idle': '2026-03-12T17:02:11.686853Z',
     'shell.execute_reply': '2026-03-12T17:02:11.686281Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 154 entries, 2025-07-30 to 2026-03-10\nData columns (total 12 columns):\n #   Column          Non-Null Count  Dtype  \n---  ------          --------------  -----  \n 0   Close           154 non-null    float64\n 1   High            154 non-null    float64\n 2   Low             154 non-null    float64\n 3   Open            154 non-null    float64\n 4   Volume          154 non-null    int64  \n 5   Day Change %    154 non-null    float64\n 6   3m_treasury     152 non-null    float64\n 7   2yr_treasury    152 non-null    float64\n 8   10yr_treasury   152 non-null    float64\n 9   yield_curve     152 non-null    float64\n 10  VIX             154 non-null    float64\n 11  fed_funds_rate  154 non-null    float64\ndtypes: float64(11), int64(1)\nmemory usage: 15.6 KB\n"}],
   'source': 'data.info()'},
  {'cell_type': 'code',
   'execution_count': 11,
   'id': 'fb241f1b',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.690465+00:00',
     'end_time': '2026-03-12T17:02:11.695757+00:00',
     'duration': 0.005292,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.692571Z',
     'iopub.execute_input': '2026-03-12T17:02:11.692720Z',
     'iopub.status.idle': '2026-03-12T17:02:11.695145Z',
     'shell.execute_reply': '2026-03-12T17:02:11.694894Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stderr',
     'text': "/var/folders/3n/hh67zc0j3vl1gh8dpln88fv40000gn/T/ipykernel_25933/1399603370.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n  data = data.fillna(method='ffill')\n"}],
   'source': "#show null rows\ndata[data.isnull().any(axis=1)]\n#nulls in 3m_treasury, 2 yr 10 yr, vix ,fed funds, solve with ffill\ndata = data.fillna(method='ffill')"},
  {'cell_type': 'code',
   'execution_count': 12,
   'id': '1d59cf39',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.697292+00:00',
     'end_time': '2026-03-12T17:02:11.703763+00:00',
     'duration': 0.006471,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.699045Z',
     'iopub.execute_input': '2026-03-12T17:02:11.699175Z',
     'iopub.status.idle': '2026-03-12T17:02:11.703074Z',
     'shell.execute_reply': '2026-03-12T17:02:11.702813Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nDatetimeIndex: 154 entries, 2025-07-30 to 2026-03-10\nData columns (total 12 columns):\n #   Column          Non-Null Count  Dtype  \n---  ------          --------------  -----  \n 0   Close           154 non-null    float64\n 1   High            154 non-null    float64\n 2   Low             154 non-null    float64\n 3   Open            154 non-null    float64\n 4   Volume          154 non-null    int64  \n 5   Day Change %    154 non-null    float64\n 6   3m_treasury     154 non-null    float64\n 7   2yr_treasury    154 non-null    float64\n 8   10yr_treasury   154 non-null    float64\n 9   yield_curve     154 non-null    float64\n 10  VIX             154 non-null    float64\n 11  fed_funds_rate  154 non-null    float64\ndtypes: float64(11), int64(1)\nmemory usage: 15.6 KB\n"}],
   'source': 'data.info()'},
  {'cell_type': 'code',
   'execution_count': 13,
   'id': 'f0b749d5',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.705361+00:00',
     'end_time': '2026-03-12T17:02:11.711582+00:00',
     'duration': 0.006221,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.707409Z',
     'iopub.execute_input': '2026-03-12T17:02:11.707584Z',
     'iopub.status.idle': '2026-03-12T17:02:11.710951Z',
     'shell.execute_reply': '2026-03-12T17:02:11.710680Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',
     'text': "<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 186 entries, 0 to 185\nData columns (total 4 columns):\n #   Column                Non-Null Count  Dtype  \n---  ------                --------------  -----  \n 0   Date                  186 non-null    object \n 1   Overnight_Return      186 non-null    float64\n 2   Overnight_Volatility  186 non-null    float64\n 3   Futures_Last_Price    186 non-null    float64\ndtypes: float64(3), object(1)\nmemory usage: 5.9+ KB\n"}],
   'source': 'futures.info()\n'},
  {'cell_type': 'code',
   'execution_count': 14,
   'id': '5e21c4db',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.713277+00:00',
     'end_time': '2026-03-12T17:02:11.718925+00:00',
     'duration': 0.005648,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.715128Z',
     'iopub.execute_input': '2026-03-12T17:02:11.715252Z',
     'iopub.status.idle': '2026-03-12T17:02:11.718131Z',
     'shell.execute_reply': '2026-03-12T17:02:11.717817Z'}},
   'outputs': [],
   'source': "#convert futures to date time index\nfutures['Date'] = pd.to_datetime(futures['Date'])\nfutures.index = futures['Date']\nfutures = futures.drop(columns=['Date'])"},
  {'cell_type': 'code',
   'execution_count': 15,
   'id': 'ee4ed504',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.720642+00:00',
     'end_time': '2026-03-12T17:02:11.725857+00:00',
     'duration': 0.005215,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.722473Z',
     'iopub.execute_input': '2026-03-12T17:02:11.722595Z',
     'iopub.status.idle': '2026-03-12T17:02:11.725231Z',
     'shell.execute_reply': '2026-03-12T17:02:11.725010Z'}},
   'outputs': [],
   'source': "#Merge with consolidated data\ndata = pd.merge(data, futures, on='Date', how='left')"},
  {'cell_type': 'code',
   'execution_count': 16,
   'id': 'b98b7f65',
   'metadata': {'tags': [],
    'papermill': {'exception': False,
     'start_time': '2026-03-12T17:02:11.727212+00:00',
     'end_time': '2026-03-12T17:02:11.732495+00:00',
     'duration': 0.005283,
     'status': 'completed'},
    'execution': {'iopub.status.busy': '2026-03-12T17:02:11.728838Z',
     'iopub.execute_input': '2026-03-12T17:02:11.728933Z',
     'iopub.status.idle': '2026-03-12T17:02:11.731859Z',
     'shell.execute_reply': '2026-03-12T17:02:11.731640Z'}},
   'outputs': [{'output_type': 'stream',
     'name': 'stdout',

In [8]:
### Execute api pulls
pm.execute_notebook('pull_api.ipynb', 'pull_api_output.ipynb')

### Read in data

#load in kalshi ticker data
kalshi_df = pd.read_csv("kalshi_full_data.csv")

#load in kalshi markets data to get open and close times for filtering
markets_df = pd.read_csv("kalshi_markets.csv")

#select columns with open and close times
markets_df_cols = markets_df[["close_time", "open_time", "ticker"]]

Executing:   0%|          | 0/3 [00:00<?, ?cell/s]

FileNotFoundError: [Errno 2] No such file or directory: '/Users/marcotaylhardat/Documents/ML/kalshi_full_data.csv'

In [ ]:
### Manipulate datetime to get closest ticker to timestamp (eliminate bets for future fed decisions)

# extract ticker suffix to indicate which bet is being made
kalshi_df['ticker_suffix'] = kalshi_df['ticker'].str.split('-').str[-1]

# merge to get open and close times for each ticker
kalshi_w_markets = pd.merge(kalshi_df, markets_df_cols, left_on='ticker', right_on='ticker', how='left')

# parse as UTC then convert to Eastern Time
kalshi_w_markets['close_time'] = pd.to_datetime(kalshi_w_markets['close_time'], utc=True).dt.tz_convert('US/Eastern')
kalshi_w_markets['open_time'] = pd.to_datetime(kalshi_w_markets['open_time'], utc=True).dt.tz_convert('US/Eastern')
kalshi_w_markets['timestamp'] = pd.to_datetime(kalshi_w_markets['timestamp'], utc=True).dt.tz_convert('US/Eastern')

# calculate how much time to close
kalshi_w_markets['time_to_close'] = (kalshi_w_markets['close_time'] - kalshi_w_markets['timestamp']).dt.total_seconds()

# rank within each timestamp group so the smallest time_to_close gets rank 1 per timestamp
kalshi_w_markets['close_rank'] = kalshi_w_markets.groupby('timestamp')['time_to_close']\
    .rank(method='dense', ascending=True)

# take only closest ticker
kalshi_w_markets = kalshi_w_markets[kalshi_w_markets['close_rank'] == 1]

In [ ]:
### Widen data to have it at timestamp level

# widen 
kalshi_df_wide = kalshi_w_markets.pivot_table(index=["timestamp"], columns="ticker_suffix", values=["volume", "open", "high", "low", "close", "mean", "open_interest"]).reset_index()

# flatten multiindex columns into single level
kalshi_df_wide.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in kalshi_df_wide.columns
]

# extract weekday and hour from timestamp
kalshi_df_wide['wd'] = kalshi_df_wide['timestamp'].dt.weekday 
kalshi_df_wide['hour'] = kalshi_df_wide['timestamp'].dt.hour

#categorize if markets are asleep
kalshi_df_wide['off_hours'] = (
((kalshi_df_wide['wd'] >= 0) & (kalshi_df_wide['wd'] <= 3) & (kalshi_df_wide['hour'] >= 17)) # Mon‑Thu after 5pm
| ((kalshi_df_wide['wd'] >= 1) & (kalshi_df_wide['wd'] <= 4) & (kalshi_df_wide['hour'] < 9)) # Tue‑Fri before 9am
| (kalshi_df_wide['wd'] >= 5) # Sat/Sun all day
| ((kalshi_df_wide['wd'] == 4) & (kalshi_df_wide['hour'] >= 17)) # Fri after 5pm (covers Fri‑Mon weekend block)
| ((kalshi_df_wide['wd'] == 0) & (kalshi_df_wide['hour'] < 9)) # Mon before 9am (end of weekend)
)

#categorize if markets have just closed
kalshi_df_wide['market_close'] = (
((kalshi_df_wide['wd'] >= 0) & (kalshi_df_wide['wd'] <= 4) & (kalshi_df_wide['hour'] == 17)) # Mon‑Thu after 5pm
# Mon before 9am (end of weekend)
)

#categorize if markets are bout to open
kalshi_df_wide['market_open'] = (
((kalshi_df_wide['wd'] >= 0) & (kalshi_df_wide['wd'] <= 4) & (kalshi_df_wide['hour'] == 9)) # Mon‑Thu at 9am # Mon before 9am (end of weekend)
)

#categorize if we are in weekend period
kalshi_df_wide['weekend_close_period'] = (
(kalshi_df_wide['wd'] >= 5) # Sat/Sun all day
| ((kalshi_df_wide['wd'] == 4) & (kalshi_df_wide['hour'] >= 17)) # Fri after 5pm (covers Fri‑Mon weekend block)
| ((kalshi_df_wide['wd'] == 0) & (kalshi_df_wide['hour'] < 9)) # Mon before 9am (end of weekend)
)

In [ ]:
# fill in nas with 0 (we are assuming that na corresponds to a paused market hence 0 trading volume 0 price)
kalshi_df_wide = kalshi_df_wide.fillna(0)

# compute an expected rate column based on open interest (total volume across ticker lifetime) of trades per ticker (exclude extreme cuts/hikes)
kalshi_df_wide['exp_rate_open_interest'] = (
    -0.25 * kalshi_df_wide['open_interest_C25']
    + 0 * kalshi_df_wide['open_interest_H0']
    + 0.25 * kalshi_df_wide['open_interest_H25']
) / (
    kalshi_df_wide['open_interest_H0']
    + kalshi_df_wide['open_interest_H25']
    + kalshi_df_wide['open_interest_C25']
)

# compute an expected rate column based on volumes of trades per ticker (exclude extreme cuts/hikes)

kalshi_df_wide['exp_rate'] = (
    -0.25 * kalshi_df_wide['volume_C25']
    + 0 * kalshi_df_wide['volume_H0']
    + 0.25 * kalshi_df_wide['volume_H25']
) / (
    kalshi_df_wide['volume_H0']
    + kalshi_df_wide['volume_H25']
    + kalshi_df_wide['volume_C25']
)

kalshi_df_wide = kalshi_df_wide.fillna(0)

# !!!!!!!! Need to know how will aggregated sp data to merge
# Create a column with relevant date based on timestamp
# - weeknight after 5pm -> same day
# - weeknight before 9am -> previous day
# - weekend (Fri 5pm through Sun) -> following Monday
# - Monday before 9am also counts as Monday

def compute_relevant_date(ts):
    wd = ts.weekday()
    hour = ts.hour

    # weekend closed period assigns next Monday
    if wd == 4 and hour >= 17:  # Fri evening
        return (ts + pd.Timedelta(days=3)).date()
    if wd == 5:  # Saturday
        return (ts + pd.Timedelta(days=2)).date()
    if wd == 6:  # Sunday
        return (ts + pd.Timedelta(days=1)).date()

    # Monday before 9am still considered Monday
    #if wd == 0 and hour < 9:
    #    return ts.date()

    # normal weekday logic
    if hour >= 17:
        return (ts + pd.Timedelta(days=1)).date()
    if hour < 9:
        return ts.date()
    return ts.date()

kalshi_df_wide['relevant_date'] = kalshi_df_wide['timestamp'].apply(compute_relevant_date)

#kalshi_df_wide.to_csv("/Users/marcotaylhardat/Documents/ML/inf_check.csv", index=True)

In [ ]:
### Filter to only keep off hours and not weekend close period (we want to see if we can predict overnight price changes based on volume and open interest patterns)
kalshi_df_wide_filtered = kalshi_df_wide[kalshi_df_wide['off_hours']]
kalshi_df_wide_filtered.to_csv("check.csv", index=True)
#kalshi_df_wide_filtered = kalshi_df_wide_filtered[~kalshi_df_wide_filtered['weekend_close_period']]

In [ ]:
### Aggregate at overnight level

# Function to calculate % change from first non-zero value to last value in overnight period
def pct_change_start_end(series):
    if len(series) < 2:
        return 0
    
    # Find the first non-zero value
    non_zero_mask = series != 0
    if not non_zero_mask.any():
        return 0  # No non-zero values
    first_non_zero_idx = non_zero_mask.idxmax()  
    start_val = series.loc[first_non_zero_idx]
    end_val = series.iloc[-1]
    if start_val == 0:
        return 0  
    return (end_val - start_val) / start_val

# aggregate
kalshi_grouped_overnight = kalshi_df_wide_filtered.groupby('relevant_date').agg({
    'exp_rate': pct_change_start_end,
    'exp_rate_open_interest': pct_change_start_end,
    'volume_C25': 'sum',
    'volume_H0': 'sum',
    'volume_H25': 'sum',
    'mean_C25': pct_change_start_end,
    'mean_H0': pct_change_start_end,
    'mean_H25': pct_change_start_end,
})

print(kalshi_grouped_overnight.head())
print(kalshi_grouped_overnight['exp_rate_open_interest'].mean())

                exp_rate  exp_rate_open_interest  volume_C25  volume_H0  \
relevant_date
2025-07-31     -1.000000                0.095081     30322.0   104894.0
2025-08-01     -0.174537               -0.048415    749266.0  1152393.0
2025-08-04      0.081891               -0.000429     72574.0    85485.0
2025-08-05     -0.652510                0.109144    169801.0   196020.0
2025-08-06     32.511792                0.047091    139467.0   161797.0

               volume_H25  mean_C25   mean_H0  mean_H25
relevant_date
2025-07-31           93.0 -1.000000  0.115385      -1.0
2025-08-01        11073.0  0.820513 -0.672131      -1.0
2025-08-04         7937.0 -0.027027  0.000000      -1.0
2025-08-05          108.0  0.027397 -0.105263      -1.0
2025-08-06          434.0  0.039474 -0.062500      -1.0
-0.006677321925103399

In [ ]:
### Check that number of days seems right
print(kalshi_grouped_overnight.shape)
print(kalshi_grouped_overnight.head())

(160, 8)
                exp_rate  exp_rate_open_interest  volume_C25  volume_H0  \
relevant_date
2025-07-31     -1.000000                0.095081     30322.0   104894.0
2025-08-01     -0.174537               -0.048415    749266.0  1152393.0
2025-08-04      0.081891               -0.000429     72574.0    85485.0
2025-08-05     -0.652510                0.109144    169801.0   196020.0
2025-08-06     32.511792                0.047091    139467.0   161797.0

               volume_H25  mean_C25   mean_H0  mean_H25
relevant_date
2025-07-31           93.0 -1.000000  0.115385      -1.0
2025-08-01        11073.0  0.820513 -0.672131      -1.0
2025-08-04         7937.0 -0.027027  0.000000      -1.0
2025-08-05          108.0  0.027397 -0.105263      -1.0
2025-08-06          434.0  0.039474 -0.062500      -1.0

In [ ]:
### Merge with macro data and save final dataset
#kalshi_grouped_overnight.to_csv("/Users/marcotaylhardat/Documents/ML/grouped_overnight_fix.csv", index=True)

# load in macro data
macro_df = pd.read_csv("consolidated_data.csv")
# convert Date to datetime then extract date to match kalshi format
macro_df['Date'] = pd.to_datetime(macro_df['Date']).dt.date
print(macro_df.head())

# reset index to make relevant_date a column, then rename
kalshi_grouped_overnight = kalshi_grouped_overnight.reset_index()
kalshi_grouped_overnight = kalshi_grouped_overnight.rename(columns={"relevant_date": "Date"})

# merge with macro data
kalshi_grouped_overnight = pd.merge(macro_df, kalshi_grouped_overnight, left_on='Date', right_on='Date', how='left')
print(kalshi_grouped_overnight.head())
    
kalshi_grouped_overnight.to_csv("../data/kalshi_w_macro_markets.csv", index=False)

         Date        Close         High          Low         Open      Volume  \
0  2025-07-30  6362.899902  6396.540039  6336.379883  6381.229980  5375070000
1  2025-07-31  6339.390137  6427.020020  6327.640137  6427.020020  6077080000
2  2025-08-01  6238.009766  6287.279785  6212.689941  6287.279785  5827150000
3  2025-08-04  6329.939941  6330.689941  6271.709961  6271.709961  4842580000
4  2025-08-05  6299.189941  6346.000000  6289.370117  6336.629883  5517410000

   Day Change %  3m_treasury  2yr_treasury  10yr_treasury  yield_curve    VIX  \
0     -0.287250         4.41          3.94           4.38         0.44  15.48
1     -1.363461         4.41          3.94           4.37         0.43  16.72
2     -0.783646         4.35          3.69           4.23         0.54  20.38
3      0.928455         4.35          3.69           4.22         0.53  17.52
4     -0.590849         4.34          3.72           4.22         0.50  17.85

   fed_funds_rate  Overnight_Return  Overnight_Volatility  Futures_Last_Price
0            4.33         -0.000506              0.000354             6412.25
1            4.33          0.006948              0.002083             6456.75
2            4.33         -0.022168              0.002764             6314.75
3            4.33          0.006290              0.000658             6304.00
4            4.33          0.009776              0.001891             6365.75
         Date        Close         High          Low         Open      Volume  \
0  2025-07-30  6362.899902  6396.540039  6336.379883  6381.229980  5375070000
1  2025-07-31  6339.390137  6427.020020  6327.640137  6427.020020  6077080000
2  2025-08-01  6238.009766  6287.279785  6212.689941  6287.279785  5827150000
3  2025-08-04  6329.939941  6330.689941  6271.709961  6271.709961  4842580000
4  2025-08-05  6299.189941  6346.000000  6289.370117  6336.629883  5517410000

   Day Change %  3m_treasury  2yr_treasury  10yr_treasury  ...  \
0     -0.287250         4.41          3.94           4.38  ...
1     -1.363461         4.41          3.94           4.37  ...
2     -0.783646         4.35          3.69           4.23  ...
3      0.928455         4.35          3.69           4.22  ...
4     -0.590849         4.34          3.72           4.22  ...

   Overnight_Volatility  Futures_Last_Price  exp_rate  exp_rate_open_interest  \
0              0.000354             6412.25       NaN                     NaN
1              0.002083             6456.75 -1.000000                0.095081
2              0.002764             6314.75 -0.174537               -0.048415
3              0.000658             6304.00  0.081891               -0.000429
4              0.001891             6365.75 -0.652510                0.109144

   volume_C25  volume_H0  volume_H25  mean_C25   mean_H0  mean_H25
0         NaN        NaN         NaN       NaN       NaN       NaN
1     30322.0   104894.0        93.0 -1.000000  0.115385      -1.0
2    749266.0  1152393.0     11073.0  0.820513 -0.672131      -1.0
3     72574.0    85485.0      7937.0 -0.027027  0.000000      -1.0
4    169801.0   196020.0       108.0  0.027397 -0.105263      -1.0

[5 rows x 24 columns]